stages:
  split:
    cmd: python3 src/data/split_data.py
    deps:
    - data/raw/raw.csv
    - params.yaml
    - src/data/split_data.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python3 src/data/normalize_data.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python3 src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - params.yaml
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluate:
    cmd: python3 src/models/evaluate_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/processed/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
